name: Build and Package with Nuitka

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"

    - name: Verify Python Version
      run: python --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka pyside6

    - name: Package with Nuitka
      run: |
        nuitka --show-progress --remove-output --lto=no --output-dir=./output/windows --main="video_mosaic.py" --standalone --assume-yes-for-downloads --enable-plugin=pyside6 --windows-disable-console

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-output
        path: ./output/windows

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"

    - name: Verify Python Version
      run: python --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka PySide6

    - name: Package with Nuitka
      run: |
        nuitka --output-dir=./output/linux --main="video_mosaic.py" --standalone --assume-yes-for-downloads --enable-plugin=pyside6

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux-output
        path: ./output/linux

  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install gettext
      run: |
        brew install gettext
        echo 'export DYLD_LIBRARY_PATH="/usr/local/opt/gettext/lib:$DYLD_LIBRARY_PATH"' >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        architecture: "x64"
        cache: "pip"

    - name: Verify Python Version
      run: python --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka pyside6

    - name: Package with Nuitka
      run: |
        nuitka --output-dir=./output/macos --main="video_mosaic.py" --standalone --assume-yes-for-downloads --enable-plugin=pyside6

    - name: Upload MacOS Artifact
      uses: actions/upload-artifact@v2
      with:
        name: macos-output
        path: ./output/macos
